version: "3.4"

services:
  postgres:
    container_name: payment-record-system-postgres
    image: postgres:15-alpine # Using a specific version, alpine for smaller size
    restart: always
    environment:
      POSTGRES_USER: people # Replace with your desired user
      POSTGRES_PASSWORD: pNEi4MgWQwAOU9kk3T0Z18m7WPBVdSGR # Replace with your desired password
      POSTGRES_DB: prs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://people:pNEi4MgWQwAOU9kk3T0Z18m7WPBVdSGR@dpg-d0pvq4muk2gs73a36kl0-a.oregon-postgres.render.com/prs"
    depends_on:
      - postgres

volumes:
  postgres_data:
#
