name: Deploy to VPS

on:
  workflow_run:
    workflows: ["integrate"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' }}
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      # ## Deploy to VPS using SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Navigate to the deployment directory on the VPS
            cd /root/deploy || { echo 'Failed to access deploy directory! Exiting...'; exit 1; }

            # Pull the latest code from the repository
            git pull origin main || { echo 'Git pull failed! Exiting...'; exit 1; }

            # Stop and remove existing containers
            docker-compose down || { echo 'Docker compose down failed! Exiting...'; exit 1; }

            # Build the Docker images (ensure it uses the latest code changes)
            docker-compose build || { echo 'Docker compose build failed! Exiting...'; exit 1; }


            # Restart the containers in detached mode
            docker-compose up -d || { echo 'Docker compose up failed! Exiting...'; exit 1; }

            # Check if containers are running
            docker ps || { echo 'Docker containers not running! Exiting...'; exit 1; }
